version = 0.1
[default]
[default.global.parameters]
stack_name = "vreddit-bot-dev"
[default.deploy]
[default.deploy.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o69yjxke7qem"
s3_prefix = "vreddit-bot-dev"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["VideoDownloadFunction=192461062174.dkr.ecr.eu-central-1.amazonaws.com/vredditbotdev075d0aec/videodownloadfunction3bdd41ccrepo"]
[default.logs.parameters]
name = "VideoDownloadFunction"

[staging]
[staging.global.parameters]
stack_name = "vreddit-bot-staging"
[staging.deploy]
[staging.deploy.parameters]
stack_name = "vreddit-bot-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o69yjxke7qem"
s3_prefix = "vreddit-bot-staging"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["VideoDownloadFunction=192461062174.dkr.ecr.eu-central-1.amazonaws.com/vredditbotdev075d0aec/videodownloadfunction3bdd41ccrepo"]
[staging.logs.parameters]
name = "VideoDownloadFunction"